CREATE TABLE IF NOT EXISTS incident_events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id        VARCHAR(50)  NOT NULL,
    service            VARCHAR(100),
    severity           VARCHAR(20),
    trace_id           VARCHAR(64),
    message            TEXT,
    original_timestamp BIGINT,
    received_at        BIGINT       NOT NULL,
    ingestion_source   VARCHAR(50),
    host               VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_incident_events_incident_id ON incident_events(incident_id);
